"""
Optimization engine schemas for Sprint-8 preparation.

This module defines:
- optimization input format
- optimized route candidate output format
- cost score container
"""
from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class OptimizationAlgorithm(str, Enum):
    """Algorithm selector used during preparation stage."""

    AUTO = "AUTO"
    SA = "SA"
    GA = "GA"


class RouteNode(BaseModel):
    """A location used by the optimization engine."""

    node_id: str = Field(..., description="Unique node id")
    latitude: float = Field(..., ge=-90, le=90, description="Latitude")
    longitude: float = Field(..., ge=-180, le=180, description="Longitude")
    risk_score: float = Field(default=0.0, ge=0, le=1, description="Risk score")
    service_time_min: float = Field(default=0.0, ge=0, description="Service time in minutes")


class CostWeights(BaseModel):
    """Weights used by the base cost function."""

    distance_weight: float = Field(default=1.0, ge=0, description="Distance weight")
    duration_weight: float = Field(default=0.3, ge=0, description="Duration weight")
    risk_weight: float = Field(default=2.0, ge=0, description="Risk weight")


class OptimizationInput(BaseModel):
    """Input format for route optimization preparation."""

    start_node: RouteNode = Field(..., description="Route start node")
    target_nodes: List[RouteNode] = Field(..., min_length=1, description="Nodes to visit")
    algorithm: OptimizationAlgorithm = Field(default=OptimizationAlgorithm.AUTO)
    max_candidates: int = Field(default=20, ge=1, le=200)
    random_seed: Optional[int] = Field(default=None, description="Optional random seed")
    average_speed_kmh: float = Field(default=50.0, gt=0, description="Average travel speed")
    weights: CostWeights = Field(default_factory=CostWeights)


class OptimizedRouteCandidate(BaseModel):
    """A candidate route generated by optimization engine base."""

    algorithm_hint: OptimizationAlgorithm = Field(..., description="Selected algorithm hint")
    ordered_node_ids: List[str] = Field(..., min_length=1)
    total_distance_km: float = Field(..., ge=0)
    total_duration_min: float = Field(..., ge=0)
    aggregated_risk_score: float = Field(..., ge=0)


class OptimizationOutput(BaseModel):
    """Output format requested by story: candidate + cost score."""

    optimized_route_candidate: OptimizedRouteCandidate
    cost_score: float = Field(..., ge=0, description="Final weighted cost score")
    generated_candidates: int = Field(..., ge=1, description="Number of evaluated candidates")
